server:
#  servlet-path: /pipe   # custom servlet-path
  port: 8080            # default server port, if not set otherwise
  max-http-header-size: 10000000

# Math AST Renderer - Main URL
mast.url: https://vmext.wmflabs.org/

# the latexml config is given from MathMLTools!
latexml:
  # use this config to control whether latexml should be called locally or remote
  remote: false
  # set special url if remote is true
  # url: https://drmf-latexml.wmflabs.org
  # set this option if you want to parse tex with semantic macros (default is true)
  content: true
  # if 'content' is true, specify the path to the macros
  contentPath: ~/Projects/DRMF

# Mathoid - alternative Latex to MathML converter
mathoid:
  active: true
  url: http://localhost:10044/mml

# change this to your local path of the translator program
translator:
  jarPath: "/home/andre/Projects/LaCASt/bin/latex-to-cas-translator.jar"

basexserver:
  harvestPath: "sampleHarvest.xml"